version: '3'
services:
  river_raid:
    build: 
      context: '.'
      args:
        DISPLAY: $DISPLAY
    image: river_raid:maven 
    container_name: river_raid
    working_dir: /app
    command: tail -f /dev/null
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
    network_mode: host